version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
    networks:
      - network
    volumes:
      - react-volume:/frontend/build
    stdin_open: true
    tty: true
  backend:
    build:
      context: ./backend
    networks:
      - network
    volumes:
      - static-volume:/home/michael-shop/backend/staticfiles
      - media-volume:/home/michael-shop/backend/media
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
      - react-volume:/var/www/react
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  db:
    env_file:
      - ./.env
    image: postgres:13.5
    networks:
      - network
    volumes:
      - postgres-database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: michael_shop
      POSTGRES_USER: michael
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  

networks:
  network:

volumes:
  static-volume:
  media-volume:
  postgres-database:
  react-volume: